import {
  NetRulesManager,
  CSPController,
  UserAgentController,
  ArkoseController,
  BusController,
  LifecycleManager,
  HTOSRequestLifecycleManager,
  utils,
} from "./core/vendor-exports.js";
import { SWBootstrap } from "./HTOS/ServiceWorkerBootstrap.js";
import { ClaudeAdapter } from "./providers/claude-adapter.js";
import { GeminiAdapter } from "./providers/gemini-adapter.js";
import { ChatGPTAdapter } from "./providers/chatgpt-adapter.js";
import { ClaudeProviderController } from "./providers/claude.js";
import { GeminiProviderController } from "./providers/gemini.js";
import { ChatGPTProviderController } from "./providers/chatgpt.js";
import { Orchestrator } from "./orchestrator/orchestrator.js";

// Ensure fetch is correctly bound in WorkerGlobalScope to avoid Illegal invocation
try {
  if (typeof fetch === "function" && typeof globalThis !== "undefined") {
    // Some environments require binding fetch to the global scope object
    globalThis.fetch = fetch.bind(globalThis);
  }
} catch (_) {}

// =============================================================================
// OFFSCREEN DOCUMENT LIFECYCLE CONTROLLER (Correctly placed here)
// =============================================================================
const OffscreenController = {
  async init() {
    console.log('[Service Worker] Initializing offscreen document controller...');
    await this._createOffscreenPageIfMissing();
  },

  async _createOffscreenPageIfMissing() {
    try {
      const hasDocument = await chrome.offscreen.hasDocument();
      if (!hasDocument) {
        console.log('[Service Worker] No offscreen document found. Creating one...');
        await chrome.offscreen.createDocument({
          url: 'offscreen.html',
          reasons: [chrome.offscreen.Reason.BLOBS, chrome.offscreen.Reason.DOM_PARSER],
          justification: 'HTOS needs offscreen DOM for image/canvas and stable bus iframe',
        });
        console.log('[Service Worker] Offscreen document created successfully.');
      } else {
        console.log('[Service Worker] Offscreen document already exists.');
      }
    } catch (error) {
      console.error('[Service Worker] Failed to create offscreen document:', error);
      throw error;
    }
  }
};

// Simple in-memory session store for continuation metadata and results
// Shape: {
//   [sessionId]: {
//     originalPrompt: string,
//     providers: {
//       [providerId]: { text: string, meta: any }
//     }
//   }
// }
const __HTOS_SESSIONS = (self.__HTOS_SESSIONS = self.__HTOS_SESSIONS || {});

function buildSynthesisPrompt(originalPrompt, otherResults, selfProviderId) {
  // Mirrors the structured reasoning pattern used in bootstrap
  const other = (otherResults || []).filter(
    (r) => r.providerId !== selfProviderId
  );
  const block = other
    .map((r) => `Response from ${r.providerId}:\n${r.text || ""}`)
    .join("\n\n---\n\n");
  return `You are a synthesis agent operating in a continuation context. You have access to your own output from the batch stage via this tab's persistent chat history. You are now tasked with synthesizing an improved version by comparing your output to one or more outputs generated by other models.

Follow this structured reasoning pattern:
1. Analyze the provided output(s) from other models. Identify strengths, weaknesses, redundancies, contradictions, and areas of unique insight.
2. Evaluate how your own batch-stage output (available in this chat) compares. Determine which ideas, phrasings, or reasoning steps are stronger, clearer, or better aligned with the user's goals.
3. Integrate the best elements from all available outputs — including your own — into a single, superior synthesis. Do not privilege your own output unless it is demonstrably stronger.
4. Refine the final result for clarity, coherence, and strategic alignment with the Hybrid Thinking OS principles (e.g., multi-perspective reasoning, insight density, goal alignment).

Original user prompt: "${originalPrompt}"

--- Other Model Outputs for Comparison ---
${block}
--- End of Other Model Outputs ---

Begin Synthesis:`;
}

// Port connection handler for popup communication
chrome.runtime.onConnect.addListener((port) => {
  console.log("[htos] Port connected:", port.name);

  if (port.name === "htos-popup") {
    port.onMessage.addListener(async (message) => {
      console.log("[htos] Message from popup:", message);

      if (message.type === "sendPrompt") {
        const { prompt, providers } = message;

        // Send acknowledgment
        port.postMessage({
          type: "result",
          data: {
            providerId: "system",
            text: `Processing request for ${providers.length} provider(s)...`,
            ok: true,
          },
        });

        // Prefer orchestrator for batch prompting if initialized
        try {
          if (self.orchestrator) {
            const includeProviderIds = (providers || []).map((p) =>
              String(p).toLowerCase()
            );
            const res = await self.orchestrator.batchPrompt(prompt, {
              includeProviderIds,
              onPartial: (pid, chunk) => {
                try {
                  if (chunk && chunk.partial) {
                    port.postMessage({
                      type: "result",
                      data: {
                        providerId: pid,
                        text: chunk.text,
                        ok: true,
                        partial: true,
                      },
                    });
                  }
                } catch (_) {}
              },
            });
            // Emit final results
            for (const r of res?.raw || []) {
              port.postMessage({
                type: "result",
                data: {
                  providerId: r.providerId,
                  text: r.text,
                  ok: r.ok,
                  partial: false,
                },
              });
            }
            return;
          }
        } catch (e) {
          console.warn(
            "[htos] orchestrator path failed, falling back to manual",
            e
          );
        }

        // Process each provider with real implementations
        for (const provider of providers) {
          try {
            let adapter;

            // Get the appropriate adapter
            switch (provider.toLowerCase()) {
              case "claude":
                adapter = self.claudeAdapter;
                break;
              case "gemini":
                adapter = self.geminiAdapter;
                break;
              case "chatgpt":
                adapter = self.chatgptAdapter;
                break;
              default:
                throw new Error(`Unknown provider: ${provider}`);
            }

            if (!adapter) {
              throw new Error(`Provider ${provider} not initialized`);
            }

            // Create request object
            const request = {
              originalPrompt: prompt,
              meta: {},
            };

            // Send prompt to real provider
            const result = await adapter.sendPrompt(
              request,
              (chunk) => {
                // Handle streaming chunks if supported
                if (chunk.partial) {
                  port.postMessage({
                    type: "result",
                    data: {
                      providerId: provider,
                      text: chunk.text,
                      ok: true,
                      partial: true,
                    },
                  });
                }
              },
              new AbortController().signal
            );

            // Send final result
            port.postMessage({
              type: "result",
              data: {
                providerId: provider,
                text: result.text,
                ok: result.ok,
                partial: false,
              },
            });
          } catch (error) {
            console.error(`[htos] Error with provider ${provider}:`, error);
            port.postMessage({
              type: "result",
              data: {
                providerId: provider,
                text: error.message || "Provider error occurred",
                ok: false,
              },
            });
          }
        }
      }
    });

    port.onDisconnect.addListener(() => {
      console.log("[htos] Port disconnected:", port.name);
    });
  }
});

// Open dedicated UI tab on action click
try {
  if (chrome.action && chrome.tabs) {
    chrome.action.onClicked.addListener(async () => {
      try {
        const url = chrome.runtime.getURL("ui/index.html");
        const existing = await chrome.tabs.query({ url: [url] });
        if (existing && existing.length > 0) {
          const t = existing[0];
          if (t.id) await chrome.tabs.update(t.id, { active: true });
          if (t.windowId != null)
            await chrome.windows.update(t.windowId, { focused: true });
        } else {
          await chrome.tabs.create({ url });
        }
      } catch (e) {
        console.error("[htos] Failed to open UI tab:", e);
      }
    });
  }
} catch (e) {
  console.warn("[htos] action click handler init failed", e);
}

(async () => {
  try {
    // Check if chrome.alarms API is available before init
    if (chrome.alarms) {
      await NetRulesManager.init();
      CSPController.init();
      await UserAgentController.init();
      if (typeof ArkoseController !== "undefined") {
        await ArkoseController.init();
      }
    } else {
      console.warn(
        "[htos] chrome.alarms API not available, skipping dependent initializations"
      );
    }
  } catch (e) {
    console.error("[htos] NetRules init failed", e);
  }

  // Initialize the offscreen document from the service worker
  try {
    await OffscreenController.init();
  } catch (e) {
    console.error('[htos] OffscreenController init failed', e);
  }

  try {
    if (typeof BusController !== "undefined") {
      await BusController.init();
      self.bus = BusController;
    }
  } catch (e) {
    console.error("[htos] Bus init failed", e);
  }

  // Initialize provider controllers and adapters
  try {
    self.claudeController = new ClaudeProviderController();
    self.geminiController = new GeminiProviderController();
    self.chatgptController = new ChatGPTProviderController();

    await self.claudeController.init();
    await self.geminiController.init();
    await self.chatgptController.init();

    self.claudeAdapter = new ClaudeAdapter(self.claudeController);
    self.geminiAdapter = new GeminiAdapter(self.geminiController);
    self.chatgptAdapter = new ChatGPTAdapter(self.chatgptController);

    await self.claudeAdapter.init();
    await self.geminiAdapter.init();
    await self.chatgptAdapter.init();

    console.log("[htos] Provider adapters initialized");

    // Initialize lifecycle + orchestrator engine
    try {
      self.lifecycleManager = new LifecycleManager();
      self.requestLifecycle = new HTOSRequestLifecycleManager(utils, {});
      self.requestLifecycle.init?.();
      self.orchestrator = new Orchestrator(
        [self.claudeAdapter, self.geminiAdapter, self.chatgptAdapter],
        {
          perProviderTimeoutMs: 30000,
          globalTimeoutMs: 45000,
          maxProviders: 8,
        },
        self.lifecycleManager,
        self.requestLifecycle
      );
      console.log(
        "[htos] Orchestrator initialized with providers:",
        self.orchestrator.listProviders().map((p) => p.id)
      );
    } catch (e) {
      console.error("[htos] Orchestrator init failed", e);
    }
  } catch (e) {
    console.error("[htos] Provider initialization failed", e);
  }

  console.log("[htos] background bootstrap complete");
})();

SWBootstrap.init();

// Handle extension installation/update
chrome.runtime.onInstalled.addListener((details) => {
  console.log("[htos] Extension installed/updated:", details.reason);

  if (details.reason === "install") {
    console.log("[htos] First time installation");
    // Initialize default settings if needed
  } else if (details.reason === "update") {
    console.log(
      "[htos] Extension updated from version:",
      details.previousVersion
    );
  }
});

// Message handler for other extension communication
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  console.log("[htos] Message received:", request, "from:", sender);

  // Handle CSP bypass request
  if (request.type === "bypassCSP" && sender.tab) {
    // TODO: Implement CSP bypass logic
    sendResponse({ success: true });
  }

  // Handle UI workflow execution
  if (request.type === "EXECUTE_WORKFLOW" && request.payload) {
    (async () => {
      const workflow = request.payload || {};
      const context = workflow.context || {};
      const steps = Array.isArray(workflow.steps) ? workflow.steps : [];
      const isSynthesis =
        steps.length === 1 && steps[0]?.stepId === "synthesis_step";

      /** Returns provider adapter by id */
      const getAdapter = (providerId) => {
        switch (String(providerId).toLowerCase()) {
          case "claude":
            return self.claudeAdapter;
          case "gemini":
            return self.geminiAdapter;
          case "chatgpt":
            return self.chatgptAdapter;
          default:
            return null;
        }
      };

      try {
        const sessionId = context.sessionId || `sid-${Date.now()}`;
        const session = (__HTOS_SESSIONS[sessionId] = __HTOS_SESSIONS[
          sessionId
        ] || { originalPrompt: "", providers: {} });

        if (isSynthesis && self.orchestrator) {
          const synthesisProvider = steps[0]?.provider;
          // Gather original prompt and other results from session (fallback to variables)
          const originalPrompt =
            session.originalPrompt ||
            context?.variables?.originalPrompt ||
            steps[0]?.payload?.prompt ||
            "";
          let otherResults = Object.entries(session.providers).map(
            ([pid, v]) => ({ providerId: pid, text: v?.text || "" })
          );
          if (
            otherResults.length === 0 &&
            context?.variables?.allBatchResults
          ) {
            otherResults = Object.entries(
              context.variables.allBatchResults
            ).map(([pid, text]) => ({ providerId: pid, text: String(text) }));
          }
          // Continuation tokens to preserve provider context
          const meta = {};
          if (synthesisProvider === "claude") {
            meta.chatId = session.providers?.claude?.meta?.chatId || undefined;
          } else if (synthesisProvider === "gemini") {
            meta.cursor = session.providers?.gemini?.meta?.cursor || undefined;
          }
          const res = await self.orchestrator.batchPrompt(originalPrompt, {
            synthesis: {
              only: true,
              providerId: synthesisProvider,
              otherResults,
              meta,
            },
            onPartial: (_pid, chunk) => {
              try {
                if (chunk && chunk.partial) {
                  chrome.runtime.sendMessage({
                    type: "SYNTHESIS_PARTIAL",
                    sessionId,
                    payload: {
                      provider: synthesisProvider,
                      text: chunk.text || "",
                    },
                  });
                }
              } catch (e) {
                console.warn("[htos] Failed to stream synthesis partial", e);
              }
            },
          });
          const s = res?.synthesis || null;
          // Persist synthesis result back into session
          session.providers[synthesisProvider] = {
            text: s?.text || "",
            meta: s?.meta || {},
          };
          chrome.runtime.sendMessage({
            type: "SYNTHESIS_COMPLETE",
            sessionId,
            payload: [{ provider: synthesisProvider, response: s?.text || "" }],
          });
        } else {
          // Batch fan-out via orchestrator; store continuation tokens and outputs
          const originalPrompt =
            context?.variables?.originalPrompt ||
            steps[0]?.payload?.prompt ||
            "";
          if (!session.originalPrompt)
            session.originalPrompt = String(originalPrompt || "");

          if (self.orchestrator) {
            const includeProviderIds = steps.map((step) =>
              String(step.provider).toLowerCase()
            );
            const res = await self.orchestrator.batchPrompt(originalPrompt, {
              includeProviderIds,
            });
            // Store for continuation
            for (const r of res?.raw || []) {
              session.providers[r.providerId] = {
                text: r?.text || "",
                meta: r?.meta || {},
              };
            }
            // Build step results preserving order
            const stepResults = steps.map((step) => {
              const r = (res?.raw || []).find(
                (x) => x.providerId === step.provider
              );
              if (!r || r.ok === false) {
                return {
                  stepId: step.stepId,
                  status: "failed",
                  error: r?.errorCode || "provider_failed",
                };
              }
              return {
                stepId: step.stepId,
                status: "completed",
                result: { response: r.text ?? "" },
              };
            });
            chrome.runtime.sendMessage({
              type: "WORKFLOW_COMPLETE",
              sessionId,
              payload: { stepResults },
            });
          } else {
            // Fallback: previous manual loop
            const stepResults = [];
            for (const step of steps) {
              try {
                const adapter = getAdapter(step.provider);
                if (!adapter)
                  throw new Error(`Unsupported provider: ${step.provider}`);
                const req = { originalPrompt, meta: {} };
                const res = await adapter.sendPrompt(
                  req,
                  undefined,
                  new AbortController().signal
                );
                session.providers[step.provider] = {
                  text: res?.text || "",
                  meta: res?.meta || {},
                };
                if (res?.ok === false)
                  stepResults.push({
                    stepId: step.stepId,
                    status: "failed",
                    error: res?.errorCode || "provider_failed",
                  });
                else
                  stepResults.push({
                    stepId: step.stepId,
                    status: "completed",
                    result: { response: res?.text ?? "" },
                  });
              } catch (err) {
                console.error("[htos] Workflow step failed", step?.stepId, err);
                stepResults.push({
                  stepId: step?.stepId || "unknown",
                  status: "failed",
                  error: err?.message || String(err),
                });
              }
            }
            chrome.runtime.sendMessage({
              type: "WORKFLOW_COMPLETE",
              sessionId,
              payload: { stepResults },
            });
          }
        }
      } catch (e) {
        console.error("[htos] Failed to execute workflow", e);
      }
    })();

    // No async sendResponse used
    return false;
  }

  // Minimal history endpoints to keep UI stable (return empty data)
  if (request.type === "GET_FULL_HISTORY") {
    try {
      sendResponse && sendResponse({ success: true, data: { sessions: [] } });
    } catch (_) {}
    return true;
  }
  if (request.type === "GET_HISTORY_SESSION") {
    try {
      sendResponse &&
        sendResponse({
          success: true,
          data: {
            id: request.payload?.sessionId,
            sessionId: request.payload?.sessionId,
            title: "Session",
            messages: [],
          },
        });
    } catch (_) {}
    return true;
  }
  if (request.type === "GET_LAST_ESCALATION") {
    try {
      sendResponse && sendResponse({ success: true, data: null });
    } catch (_) {}
    return true;
  }

  // Return true to indicate async response
  return true;
});
